#!/bin/bash
# Builds Heft optimised and installs it into /Applications.
#
#   Scripts/install.sh              # build, install, and open it
#   Scripts/install.sh --install-only # build and install, but leave it closed
#   Scripts/install.sh --to ~/Applications
#
# Installing means copying the bundle: there is no installer package or
# notarisation. The build uses a local Apple Development certificate when one
# is available, and otherwise falls back to ad-hoc signing.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DESTINATION="/Applications"
LAUNCH=1

while [[ $# -gt 0 ]]; do
    case "$1" in
        --launch)       LAUNCH=1; shift ;; # Kept for compatibility.
        --install-only) LAUNCH=0; shift ;;
        --to)           DESTINATION="${2:?--to needs a folder}"; shift 2 ;;
        *) echo "Unknown option: $1" >&2; exit 1 ;;
    esac
done

DESTINATION="${DESTINATION/#\~/$HOME}"
if [[ ! -d "$DESTINATION" ]]; then
    echo "No such folder: $DESTINATION" >&2
    exit 1
fi

TARGET="$DESTINATION/Heft.app"

"$ROOT/Scripts/bundle.sh" release
BUILT_APP="$ROOT/.build/XcodeDerivedData/Build/Products/Release/Heft.app"

# A running copy holds its bundle open, and replacing it underneath leaves the
# process on a half-deleted app.
if pgrep -x Heft >/dev/null; then
    echo "Quitting the running copy…"
    osascript -e 'tell application "Heft" to quit' >/dev/null 2>&1 || pkill -x Heft || true
    for _ in $(seq 1 20); do
        pgrep -x Heft >/dev/null || break
        sleep 0.25
    done
fi

rm -rf "$TARGET"
cp -R "$BUILT_APP" "$TARGET"

echo "Installed $TARGET"

# The `heft` command, installed the way `code .` works.
#
# ~/.local/bin rather than /usr/local/bin: the latter is root-owned, so
# installing there would need sudo, and an install script that asks for a
# password is not one anybody runs casually. The launcher is a wrapper rather
# than a symlink because the bundled binary decides what it is by argv[0],
# and it has to keep seeing itself as Heft.
CLI_DIR="$HOME/.local/bin"
mkdir -p "$CLI_DIR"
# The verb list comes from the binary itself, so the wrapper cannot fall
# behind it. It used to be written out by hand here, and drifted the first
# time a verb was added: `heft export` was rewritten to `heft open export` and
# reported "no such file or folder: export" from a binary that handled the
# verb perfectly well.
VERBS="$("$TARGET/Contents/MacOS/Heft" help --verbs 2>/dev/null | tr '\n' '|' | sed 's/|$//')"
if [[ -z "$VERBS" ]]; then
    echo "could not read the verb list from the built binary" >&2
    exit 1
fi

cat > "$CLI_DIR/heft" <<EOF
#!/bin/bash
# The Heft command line. Generated by Scripts/install.sh.
#
# A bare path is the common case and gets an implicit \`open\`, so \`heft .\`
# works the way \`code .\` does. Anything that names a verb is forwarded
# untouched — without this, \`heft find …\` would run \`open find …\` and look
# for a folder called "find".
#
# The verbs below were read from the binary at install time; see
# CommandLineSpec.swift, which is the one place they are declared.
BIN="$TARGET/Contents/MacOS/Heft"
case "\${1:-}" in
    $VERBS)
        exec "\$BIN" "\$@" ;;
    *)
        exec "\$BIN" open "\$@" ;;
esac
EOF
chmod +x "$CLI_DIR/heft"

if [[ ":$PATH:" == *":$CLI_DIR:"* ]]; then
    echo "Installed $CLI_DIR/heft"
else
    echo "Installed $CLI_DIR/heft (not on PATH; add it to use \`heft\`)"
fi

if [[ "$LAUNCH" -eq 1 ]]; then
    open "$TARGET"
fi
